source 'https://rubygems.org'

# Core
gem 'rails', '4.1.6'
gem 'rails-api'
gem 'sqlite3'

# Security / Authentication
gem 'devise' 
gem 'bcrypt'
gem 'rack-cors'
gem 'simple_token_authentication'

# Development
group :development, :test do
  gem 'rspec-rails'
  gem 'spring'
end



# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
